### ISSUE TITLE
Enhancement Request: Allow multiple A records for the same domain name (for load balance testing)

### ISSUE THREAD

**Issue by brettnolan** [Crypt0s/FakeDns#12]
It would be awesome if FakeDns allowed you to configure multiple A records for the same domain name (for load balancing).

I tried putting multiple IPs in the conf file, but it always just uses the first one instead of cycling through them.

Thanks

**Comment by Crypt0s** [comment]
Hey!

Sorry it took a while to get to this but I have started work on this.  Implementing this feature required a refactor of how I handle the parsing of requests and how I perform matching, and I've decided to merge in a few other things as well.  I hope to finish getting everything done, tested, merged, and pushed to master "really soon now".  This has been a fun feature to implement!

**Comment by Crypt0s** [comment]
Done!

Enjoy!

**Comment by brettnolan** [comment]
Awesome!  Thank you so much!
