### ISSUE TITLE
add an option to return NX DOMAIN for a regex

### ISSUE THREAD

**Issue by andyrat33** [Crypt0s/FakeDns#18]
Great tool!
It would be useful to be able to add an option to return 'no such domain' NX DOMAIN return type for a regex. So that hosts lookup can succeed for some lookups and fail for others. 
Thanks

**Comment by Crypt0s** [comment]
it does actually do this, but i've not put the example in the example configuration file -- simply put "none" (all lowercase) for the ip instead and it'll return the no such domain response!
