### ISSUE TITLE
what about adding a tunneling feature for more control and monitoring if everything is going as it should ?

### ISSUE THREAD

**Issue by minanagehsalalma** [Crypt0s/FakeDns#31]
just like what he wanted to do in the to do list in this article 
https://sinister.ly/Thread-DNS-Rebinding-Attack

> I need to make a tunnel (using JavaScript) to gain more control!

**Comment by minanagehsalalma** [comment]
@Theaxiom just like this 

https://portswigger.net/daily-swig/new-tool-enables-dns-rebinding-tunnel-attacks-without-reconnaissance

https://youtu.be/sqUxeiqq0xE

**Comment by Crypt0s** [comment]
As the articles you've linked to state, you need to have the ability to run JavaScript within the browser of a target with the ability to scan internal network ranges you do not have access to.  The DNS rebinding attacks simply facilitate this taking place.

While serving the JavaScript to a victim computer is outside of the scope of this project, you can utilize FakeDNS to perform a DNS rebinding attack.  An example of this is available in the example configuration file dns.conf.example

`A roundrobin 1.1.1.1 10%2.2.2.2,3.3.3.3,4.4.4.4`

This entry serves a type-A DNS entry named "roundrobin" as 1.1.1.1 until the 11th time that the ip address of "roundrobin" is requested, when it will switch to serving the answer as 2.2.2.2, 3.3.3.3, or 4.4.4.4 in that order.

Hopefully this answers your question.

**Comment by minanagehsalalma** [comment]
@Crypt0s so it's a no ? ;;
